-- ====================================================================
-- SQL SCRIPT: KHỞI TẠO BẢNG CƠ SỞ DỮ LIỆU "QÙA TẶNG DI LINH" VỚI TIỀN TỐ "dilinh_"
-- Hướng dẫn: Bạn truy cập vào trang quản trị Supabase -> Chọn dự án -> SQL Editor -> Tạo "New Query" -> Dán toàn bộ code dưới đây và nhấn RUN.
-- ====================================================================

-- 1. Bảng dilinh_users (Quản lý tài khoản Admin/Thành viên)
CREATE TABLE IF NOT EXISTS dilinh_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nick_name TEXT UNIQUE NOT NULL,
    pass TEXT NOT NULL,
    full_name TEXT,
    user_role TEXT DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Bảng dilinh_product (Quản lý sản phẩm đặc sản)
CREATE TABLE IF NOT EXISTS dilinh_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code TEXT UNIQUE NOT NULL,
    product_long TEXT NOT NULL,
    sale_price INTEGER DEFAULT 0 NOT NULL,
    promo_price INTEGER DEFAULT 0,
    image TEXT,
    status BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Bảng dilinh_posts (Quản lý bài viết blog, tin tức và testimonial của khách hàng)
CREATE TABLE IF NOT EXISTS dilinh_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE,
    content TEXT,
    thumbnail TEXT,
    post_type TEXT DEFAULT 'article' NOT NULL, -- 'article', 'testimonial', 'event', 'promotion'
    status BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Bảng dilinh_app_settings (Quản lý cấu hình toàn trang, layout giao diện, menu, thông tin shop)
CREATE TABLE IF NOT EXISTS dilinh_app_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ====================================================================
-- SEED DATA (Nạp dữ liệu mẫu ban đầu để chạy trang chủ và đăng nhập admin)
-- ====================================================================

-- Thêm tài khoản Admin mặc định (Nickname: dilinh_sadmin / Mật khẩu: admin123)
INSERT INTO dilinh_users (nick_name, pass, full_name, user_role)
VALUES (
    'dilinh_sadmin', 
    'admin123', 
    'Super Admin Di Linh', 
    'admin'
) ON CONFLICT (nick_name) DO NOTHING;

-- Thêm cấu hình website mặc định (Vô cùng quan trọng để hiển thị trang chủ không bị lỗi)
INSERT INTO dilinh_app_settings (key, value, description)
VALUES (
    'site_config',
    '{
        "company_info": {
            "company_name": "Đặc Sản & Quà Tặng Di Linh",
            "phone": "0901 234 567",
            "zalo": "0901 234 567",
            "email": "contact@dilinhgift.vn",
            "address": "123 Đường 25/5, TT. Di Linh, Lâm Đồng",
            "facebook": "https://fb.com/dilinhgift",
            "instagram": "https://instagram.com/dilinhgift"
        },
        "home_sections": [
            { "id": "hero", "name": "Banner chính", "visible": true, "media_url": "/qc.mp4", "media_type": "video" },
            { "id": "featured", "name": "Sản phẩm nổi bật", "visible": true },
            { "id": "process", "name": "Quy trình sản xuất", "visible": true },
            { "id": "testimonials", "name": "Khách hàng nói gì", "visible": true },
            { "id": "news", "name": "Tin tức & Cẩm nang", "visible": true },
            { "id": "partners", "name": "Đối tác liên kết", "visible": true }
        ],
        "partners": [
            { "name": "VietGAP Di Linh", "logo": "https://images.unsplash.com/photo-1594897030264-ab7d87efc473?auto=format&fit=crop&q=80&w=300" },
            { "name": "Lâm Đồng Organics", "logo": "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&q=80&w=300" }
        ],
        "menu": [
            { "id": "home", "name": "Trang chủ", "path": "/" },
            { "id": "about", "name": "Giới thiệu", "path": "/gioi-thieu" },
            { "id": "products", "name": "Sản phẩm", "path": "/san-pham" },
            { "id": "news", "name": "Tin tức", "path": "/tin-tuc" },
            { "id": "contact", "name": "Liên hệ", "path": "/lien-he" }
        ]
    }'::jsonb,
    'Cấu hình thông tin, bố cục trang chủ, danh sách đối tác và menu chính'
) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, description = EXCLUDED.description;

-- Thêm các sản phẩm mẫu ban đầu
INSERT INTO dilinh_product (product_code, product_long, sale_price, promo_price, image, status)
VALUES 
('M01', 'Mứt Củ Dền Sấy Dẻo', 120000, 99000, 'https://images.unsplash.com/photo-1547512111-c7a745b45f93?auto=format&fit=crop&q=80&w=800', true),
('M02', 'Mứt Gừng Mật Ong Rừng', 150000, 125000, 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=800', true),
('C01', 'Cà Phê Robusta Honey Di Linh', 220000, 180000, 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=800', true)
ON CONFLICT (product_code) DO NOTHING;

-- Thêm các bài viết và ý kiến khách hàng mẫu ban đầu
INSERT INTO dilinh_posts (title, slug, content, thumbnail, post_type, status)
VALUES
('Mẹo Chế Biến Mứt Rau Củ Không Bị Lại Đường', 'meo-che-bien-mut-rau-cu', '<p>Mứt rau củ là món ăn truyền thống, nhưng làm sao để mứt luôn dẻo ngon mà không bị kết tinh đường? Hãy cùng khám phá bí quyết từ các nghệ nhân Di Linh.</p>', 'https://images.unsplash.com/photo-1547512111-c7a745b45f93?auto=format&fit=crop&q=80&w=800', 'article', true),
('Khám Phá Cà Phê Di Linh - Niềm Tự Hào Của Cao Nguyên', 'kham-pha-ca-phe-di-linh', '<p>Bên cạnh mứt rau củ, cà phê Di Linh cũng là một thực phẩm tinh túy được cả thế giới công nhận. Tìm hiểu về hành trình từ hạt cà phê đến tách trà mứt buổi sáng.</p>', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=800', 'article', true),
('Chị Nguyễn Thị Lan', 'testimonial-1', 'Mứt củ dền ở đây ngon xuất sắc, không quá ngọt, ăn rất thơm và tốt cho sức khỏe. Gia đình mình ai cũng thích!', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200', 'testimonial', true),
('Anh Trần Minh Tuấn', 'testimonial-2', 'Cà phê vị rất đầm và thơm tự nhiên, chuẩn vị Robusta cao nguyên. Dùng làm quà tặng đối tác rất sang trọng.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200', 'testimonial', true)
ON CONFLICT (slug) DO NOTHING;

-- ====================================================================
-- CẤU HÌNH VÔ HIỆU HÓA RLS (ROW LEVEL SECURITY) - GIẢI PHÓNG TOÀN BỘ GIỚI HẠN QUYỀN
-- Giúp tài khoản Admin và ứng dụng khách (Frontend) có toàn quyền thực hiện các thao tác CRUD dữ liệu mà không bị chặn bởi chính sách bảo mật Supabase
-- ====================================================================

ALTER TABLE dilinh_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE dilinh_product DISABLE ROW LEVEL SECURITY;
ALTER TABLE dilinh_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE dilinh_app_settings DISABLE ROW LEVEL SECURITY;

-- ====================================================================
-- CẤU HÌNH BUCKET "dilinh" - LƯU TRỮ TỆP, HÌNH ẢNH, CLIP
-- Tự động khởi tạo bucket "dilinh" ở trạng thái công khai (Public) và gỡ bỏ mọi rào cản phân quyền
-- ====================================================================

-- 1. Tạo bucket "dilinh" nếu chưa tồn tại
INSERT INTO storage.buckets (id, name, public)
VALUES ('dilinh', 'dilinh', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Gỡ bỏ mọi chính sách giới hạn trên storage.objects của bucket "dilinh" để Admin upload thoải mái
DROP POLICY IF EXISTS "Allow public CRUD on dilinh bucket" ON storage.objects;
CREATE POLICY "Allow public CRUD on dilinh bucket"
ON storage.objects FOR ALL TO public
USING (bucket_id = 'dilinh')
WITH CHECK (bucket_id = 'dilinh');


